apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pndc6yhxw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pndc6yhxw-nodejs 
  name: pndc6yhxw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pndc6yhxw-nodejs 
